-- Auto-generated schema for H2 in-memory test database
-- Extracted from Flyway migrations. Disabled in FastMapperTest.

CREATE TABLE IF NOT EXISTS t_attachment (id BIGINT PRIMARY KEY, biz_type VARCHAR(32) NOT NULL, biz_id BIGINT, file_name VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, file_path VARCHAR(500) NOT NULL, bucket_name VARCHAR(64) NOT NULL, file_size BIGINT, content_type VARCHAR(128), file_hash VARCHAR(128), ocr_data JSONB, vector public.vector(768), uploaded_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS t_ai_task (id BIGINT PRIMARY KEY, task_no VARCHAR(32) NOT NULL, task_type VARCHAR(32) NOT NULL, biz_type VARCHAR(32), biz_id BIGINT, status VARCHAR(20) NOT NULL DEFAULT 'PENDING', input_data JSONB, output_data JSONB, error_message TEXT, confidence NUMERIC($1,$2), reviewed BOOLEAN DEFAULT FALSE, reviewed_by BIGINT, reviewed_at TIMESTAMP, apply_status VARCHAR(20) DEFAULT 'NOT_APPLIED', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, started_at TIMESTAMP, completed_at TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_ai_task_no UNIQUE (task_no), CONSTRAINT chk_ai_task_status CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED')), CONSTRAINT chk_ai_task_apply CHECK (apply_status IS NULL OR apply_status IN ('APPLIED', 'REJECTED', 'NOT_APPLIED')));

CREATE TABLE IF NOT EXISTS t_ai_anomaly_tag (id BIGINT PRIMARY KEY, biz_type VARCHAR(32) NOT NULL, biz_id BIGINT NOT NULL, anomaly_type VARCHAR(32) NOT NULL, severity VARCHAR(20) NOT NULL DEFAULT 'MEDIUM', description VARCHAR(500), ai_task_id BIGINT, resolved BOOLEAN DEFAULT FALSE, resolved_by BIGINT, resolved_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_anomaly_task FOREIGN KEY (ai_task_id) REFERENCES t_ai_task(id), CONSTRAINT chk_anomaly_severity CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')));

CREATE TABLE IF NOT EXISTS t_report_template (id BIGINT PRIMARY KEY, template_code VARCHAR(32) NOT NULL, template_name VARCHAR(100) NOT NULL, report_type VARCHAR(32) NOT NULL, config JSONB NOT NULL, is_system BOOLEAN DEFAULT FALSE, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_report_template_code UNIQUE (template_code));

CREATE TABLE IF NOT EXISTS t_cash_flow_rule (id BIGINT PRIMARY KEY, code VARCHAR(32) NOT NULL, name VARCHAR(100) NOT NULL, flow_type VARCHAR(20) NOT NULL, match_subject VARCHAR(200) NOT NULL, flow_item VARCHAR(64) NOT NULL, priority INTEGER DEFAULT 1, is_active BOOLEAN DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_cf_rule_code UNIQUE (code), CONSTRAINT chk_cf_flow_type CHECK (flow_type IN ('OPERATING_IN', 'OPERATING_OUT', 'INVESTING_IN', 'INVESTING_OUT', 'FINANCING_IN', 'FINANCING_OUT')));

CREATE TABLE IF NOT EXISTS t_voucher_cash_flow (id BIGINT PRIMARY KEY, voucher_id BIGINT NOT NULL, entry_id BIGINT NOT NULL, flow_type VARCHAR(20) NOT NULL, flow_item VARCHAR(64) NOT NULL, amount NUMERIC($1,$2) NOT NULL, is_manual BOOLEAN DEFAULT FALSE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_cf_voucher FOREIGN KEY (voucher_id) REFERENCES t_voucher(id), CONSTRAINT fk_cf_entry FOREIGN KEY (entry_id) REFERENCES t_voucher_entry(id) ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS t_financial_metric (id BIGINT PRIMARY KEY, metric_code VARCHAR(32) NOT NULL, metric_name VARCHAR(100) NOT NULL, category VARCHAR(32) NOT NULL, formula TEXT NOT NULL, unit VARCHAR(16) DEFAULT '%', description VARCHAR(500), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_metric_code UNIQUE (metric_code));

CREATE TABLE IF NOT EXISTS t_alert_rule (id BIGINT PRIMARY KEY, rule_code VARCHAR(32) NOT NULL, rule_name VARCHAR(100) NOT NULL, metric_code VARCHAR(32) NOT NULL, comparator VARCHAR(10) NOT NULL, threshold NUMERIC($1,$2) NOT NULL, severity VARCHAR(20) DEFAULT 'MEDIUM', notify_channels VARCHAR(200), is_active BOOLEAN DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_alert_code UNIQUE (rule_code), CONSTRAINT chk_alert_comparator CHECK (comparator IN ('GT', 'GTE', 'LT', 'LTE', 'EQ')));

CREATE TABLE IF NOT EXISTS t_cash_journal (id BIGINT PRIMARY KEY, period VARCHAR(6) NOT NULL, journal_date DATE NOT NULL, journal_no VARCHAR(32) NOT NULL, summary VARCHAR(500), debit NUMERIC($1,$2) NOT NULL DEFAULT 0, credit NUMERIC($1,$2) NOT NULL DEFAULT 0, balance NUMERIC($1,$2) NOT NULL DEFAULT 0, subject_id BIGINT NOT NULL REFERENCES t_subject(id), opposite_subject_id BIGINT REFERENCES t_subject(id), voucher_id BIGINT REFERENCES t_voucher(id), source VARCHAR(20) DEFAULT 'MANUAL', created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_cash_journal_no UNIQUE (journal_no), CONSTRAINT chk_cash_source CHECK (source IN ('MANUAL', 'AUTO', 'GENERATED')));

CREATE TABLE IF NOT EXISTS t_ticket (id BIGINT PRIMARY KEY, ticket_no VARCHAR(32) NOT NULL, ticket_type VARCHAR(20) NOT NULL, amount NUMERIC($1,$2) NOT NULL DEFAULT 0, bank_id BIGINT REFERENCES t_bank_account(id), payee VARCHAR(100), drawer VARCHAR(100), issue_date DATE NOT NULL, expire_date DATE, status VARCHAR(20) NOT NULL DEFAULT 'IN_STOCK', remark VARCHAR(500), created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_ticket_no UNIQUE (ticket_no), CONSTRAINT chk_ticket_type CHECK (ticket_type IN ('CHECK', 'DRAFT', 'CASHIER_CHECK', 'BANK_ACCEPTANCE')), CONSTRAINT chk_ticket_status CHECK (status IN ('IN_STOCK', 'ISSUED', 'ENDORSED', 'CASHED', 'VOIDED')));

CREATE TABLE IF NOT EXISTS t_ticket_transaction (id BIGINT PRIMARY KEY, ticket_id BIGINT NOT NULL REFERENCES t_ticket(id) ON DELETE CASCADE, trans_type VARCHAR(20) NOT NULL, trans_date DATE NOT NULL, recipient VARCHAR(100), amount NUMERIC($1,$2) NOT NULL DEFAULT 0, remark VARCHAR(500), operator_id BIGINT, voucher_id BIGINT REFERENCES t_voucher(id), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT chk_ticket_trans_type CHECK (trans_type IN ('ISSUE', 'ENDORSE', 'CASH', 'VOID', 'RETURN')));

CREATE TABLE IF NOT EXISTS t_beginning_control (id BIGINT PRIMARY KEY, period VARCHAR(6) NOT NULL, is_initialized BOOLEAN NOT NULL DEFAULT FALSE, is_balanced BOOLEAN NOT NULL DEFAULT FALSE, is_locked BOOLEAN NOT NULL DEFAULT FALSE, initialized_by BIGINT, initialized_at TIMESTAMP, locked_by BIGINT, locked_at TIMESTAMP, note VARCHAR(500), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT uq_begin_control_period UNIQUE (period));

CREATE TABLE IF NOT EXISTS t_budget_execution (id BIGINT PRIMARY KEY, budget_entry_id BIGINT NOT NULL REFERENCES t_budget_entry(id) ON DELETE CASCADE, period VARCHAR(6) NOT NULL, actual_amount NUMERIC($1,$2) NOT NULL DEFAULT 0, source_type VARCHAR(20) NOT NULL, source_id BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT chk_budget_exec_source CHECK (source_type IN ('VOUCHER', 'DOC', 'MANUAL')));

CREATE TABLE IF NOT EXISTS t_classification_rule (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tenant_id BIGINT NOT NULL, name VARCHAR(100) NOT NULL, rule_type VARCHAR(30) NOT NULL DEFAULT 'keyword', pattern TEXT NOT NULL, match_field VARCHAR(30) NOT NULL DEFAULT 'description', direction VARCHAR(10), classification VARCHAR(50) NOT NULL, priority INTEGER NOT NULL DEFAULT 0, is_active BOOLEAN NOT NULL DEFAULT TRUE, debit_subject_id BIGINT, credit_subject_id BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by BIGINT, updated_by BIGINT, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT fk_cls_rule_debit_subject FOREIGN KEY (debit_subject_id) REFERENCES t_subject(id), CONSTRAINT fk_cls_rule_credit_subject FOREIGN KEY (credit_subject_id) REFERENCES t_subject(id), CONSTRAINT chk_cls_rule_type CHECK (rule_type IN ('keyword', 'keyword_regex', 'counterparty_match')), CONSTRAINT chk_cls_rule_match_field CHECK (match_field IN ('description', 'counterparty')), CONSTRAINT chk_cls_rule_direction CHECK (direction IN ('in', 'out') OR direction IS NULL));

CREATE TABLE IF NOT EXISTS t_ai_feedback_log (id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, bank_txn_id BIGINT NOT NULL, ai_suggested_action VARCHAR(50), ai_confidence INTEGER, ai_business_scene VARCHAR(100), human_action VARCHAR(50) NOT NULL, human_modified_fields JSONB, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_ai_feedback_txn FOREIGN KEY (bank_txn_id) REFERENCES t_bank_statement(id), CONSTRAINT chk_ai_feedback_action CHECK (human_action IN ('CONFIRM_AI', 'MANUAL_RECLASSIFY', 'IGNORE_AI', 'BATCH_CONFIRM')));

CREATE TABLE IF NOT EXISTS t_period (id BIGINT PRIMARY KEY, year INTEGER NOT NULL, month INTEGER NOT NULL CHECK (month >= 1 AND month <= 12), period_code VARCHAR(20) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'open', created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_period_code UNIQUE (period_code), CONSTRAINT chk_period_status CHECK (status IN ('open', 'closed', 'locked')));

CREATE TABLE IF NOT EXISTS t_subject (id BIGINT PRIMARY KEY, code VARCHAR(50) NOT NULL, name VARCHAR(200) NOT NULL, parent_id BIGINT, level INTEGER NOT NULL DEFAULT 1, direction VARCHAR(10) NOT NULL DEFAULT 'debit', is_leaf BOOLEAN NOT NULL DEFAULT TRUE, aux_calc_type VARCHAR(50), is_active BOOLEAN NOT NULL DEFAULT TRUE, remark VARCHAR(500), created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_subject_code UNIQUE (code), CONSTRAINT chk_direction CHECK (direction IN ('debit', 'credit')), CONSTRAINT chk_aux_calc_type CHECK (aux_calc_type IS NULL OR aux_calc_type IN ('customer', 'vendor', 'department', 'project', 'employee')));

CREATE TABLE IF NOT EXISTS t_voucher_type (id BIGINT PRIMARY KEY, code VARCHAR(20) NOT NULL, name VARCHAR(100) NOT NULL, sort_order INTEGER NOT NULL DEFAULT 1, numbering_rule VARCHAR(100) NOT NULL DEFAULT '{type}-{year}{month}-{serial}', is_active BOOLEAN NOT NULL DEFAULT TRUE, remark VARCHAR(500), created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_voucher_type_code UNIQUE (code));

CREATE TABLE IF NOT EXISTS t_sys_config (id BIGINT PRIMARY KEY, config_key VARCHAR(100) NOT NULL, config_value TEXT, config_type VARCHAR(50) NOT NULL DEFAULT 'system', description VARCHAR(500), is_active BOOLEAN NOT NULL DEFAULT TRUE, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_config_key UNIQUE (config_key), CONSTRAINT chk_config_type CHECK (config_type IN ('system', 'business', 'accounting')));

CREATE TABLE IF NOT EXISTS t_summary_lib (id BIGINT PRIMARY KEY, summary_code VARCHAR(50), summary_text VARCHAR(500) NOT NULL, category VARCHAR(100), sort_order INTEGER NOT NULL DEFAULT 1, is_active BOOLEAN NOT NULL DEFAULT TRUE, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_summary_code UNIQUE (summary_code));

CREATE TABLE IF NOT EXISTS t_voucher_template (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL, description VARCHAR(500), classification VARCHAR(50), -- 绑定的分类: bank_fee / interest_income / tax_payment / ... number_prefix VARCHAR(20) NOT NULL DEFAULT 'JZ', -- 凭证前缀, 支持 CD-/FPS-/JZ- 等 is_active BOOLEAN NOT NULL DEFAULT TRUE, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_voucher_template_name UNIQUE (name));

CREATE TABLE IF NOT EXISTS t_voucher_template_line (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, template_id BIGINT NOT NULL, subject_id BIGINT NOT NULL, -- 借贷科目 ID dr_amount_template VARCHAR(100), -- 借方金额表达式: e.g. "{{amount}}" cr_amount_template VARCHAR(100), -- 贷方金额表达式: e.g. "{{amount}}" 或 "" summary_template VARCHAR(200), -- 摘要模板: e.g. "银行手续费 {{summary}}" direction VARCHAR(10) NOT NULL DEFAULT 'debit', -- debit / credit (指定行是借还是贷, 用于行级借贷方向) line_order INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT fk_vtl_template FOREIGN KEY (template_id) REFERENCES t_voucher_template(id) ON DELETE CASCADE, CONSTRAINT fk_vtl_subject FOREIGN KEY (subject_id) REFERENCES t_subject(id), CONSTRAINT chk_vtl_direction CHECK (direction IN ('debit', 'credit')));

CREATE TABLE IF NOT EXISTS t_reconciliation_log (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, tenant_id BIGINT NOT NULL DEFAULT 1, source_doc_type VARCHAR(32) NOT NULL, -- receipt/payment/bank_txn source_doc_id BIGINT NOT NULL, target_doc_type VARCHAR(32) NOT NULL, -- INVOICE_OUT/INVOICE_IN target_doc_id BIGINT NOT NULL, allocated_amount NUMERIC($1,$2) NOT NULL, discount_amount NUMERIC($1,$2) DEFAULT 0, match_score NUMERIC($1,$2), match_method VARCHAR(20) DEFAULT 'MANUAL', -- AUTO / MANUAL status VARCHAR(20) DEFAULT 'CONFIRMED', -- CONFIRMED / CANCELLED remark VARCHAR(500), created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT NOW());

CREATE TABLE IF NOT EXISTS t_dept (id BIGINT PRIMARY KEY, name VARCHAR(200) NOT NULL, parent_id BIGINT, sort_order INTEGER NOT NULL DEFAULT 1, status VARCHAR(20) NOT NULL DEFAULT 'active', leader VARCHAR(100), phone VARCHAR(20), email VARCHAR(100), created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT chk_dept_status CHECK (status IN ('active', 'inactive')));

CREATE TABLE IF NOT EXISTS t_user (id BIGINT PRIMARY KEY, username VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL, real_name VARCHAR(100), nickname VARCHAR(100), email VARCHAR(100), phone VARCHAR(20), avatar VARCHAR(500), dept_id BIGINT REFERENCES t_dept(id), status VARCHAR(20) NOT NULL DEFAULT 'active', remark VARCHAR(500), last_login_ip VARCHAR(50), last_login_at TIMESTAMP, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_user_username UNIQUE (username), CONSTRAINT chk_user_status CHECK (status IN ('active', 'inactive', 'locked')));

CREATE TABLE IF NOT EXISTS t_role (id BIGINT PRIMARY KEY, code VARCHAR(50) NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(500), status VARCHAR(20) NOT NULL DEFAULT 'active', sort_order INTEGER NOT NULL DEFAULT 1, data_scope VARCHAR(20) NOT NULL DEFAULT 'self', created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_role_code UNIQUE (code), CONSTRAINT chk_role_status CHECK (status IN ('active', 'inactive')), CONSTRAINT chk_role_data_scope CHECK (data_scope IN ('all', 'dept', 'self', 'custom')));

CREATE TABLE IF NOT EXISTS t_menu (id BIGINT PRIMARY KEY, name VARCHAR(100) NOT NULL, permission_code VARCHAR(100), type VARCHAR(20) NOT NULL DEFAULT 'menu', parent_id BIGINT, path VARCHAR(200), component VARCHAR(200), icon VARCHAR(100), sort_order INTEGER NOT NULL DEFAULT 1, is_active BOOLEAN NOT NULL DEFAULT TRUE, is_visible BOOLEAN NOT NULL DEFAULT TRUE, keep_alive BOOLEAN NOT NULL DEFAULT TRUE, always_show BOOLEAN NOT NULL DEFAULT FALSE, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT chk_menu_type CHECK (type IN ('menu', 'button', 'iframe', 'external')));

CREATE TABLE IF NOT EXISTS t_user_role (id BIGINT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES t_user(id), role_id BIGINT NOT NULL REFERENCES t_role(id), CONSTRAINT uq_user_role UNIQUE (user_id, role_id));

CREATE TABLE IF NOT EXISTS t_role_menu (id BIGINT PRIMARY KEY, role_id BIGINT NOT NULL REFERENCES t_role(id), menu_id BIGINT NOT NULL REFERENCES t_menu(id), CONSTRAINT uq_role_menu UNIQUE (role_id, menu_id));

CREATE TABLE IF NOT EXISTS t_audit_log (id BIGINT PRIMARY KEY, user_id BIGINT, username VARCHAR(100), operation VARCHAR(500), method VARCHAR(500), request_params JSONB, response_result JSONB, old_snapshot JSONB, new_snapshot JSONB, ip_address VARCHAR(50), user_agent VARCHAR(500), execution_time_ms INTEGER, status VARCHAR(20) NOT NULL DEFAULT 'success', module VARCHAR(100), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT chk_audit_status CHECK (status IN ('success', 'fail')));

CREATE TABLE IF NOT EXISTS t_employee (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, code VARCHAR(50), name VARCHAR(100) NOT NULL, dept_id BIGINT, phone VARCHAR(20), email VARCHAR(100), bank_name VARCHAR(100), bank_account VARCHAR(50), id_card VARCHAR(18), is_active BOOLEAN DEFAULT true, remark VARCHAR(500), created_at TIMESTAMP DEFAULT now(), updated_at TIMESTAMP DEFAULT now(), deleted INTEGER DEFAULT 0);

CREATE TABLE IF NOT EXISTS t_expense_reimbursement (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, reimb_no VARCHAR(50) NOT NULL, employee_id BIGINT NOT NULL, dept_id BIGINT, expense_type VARCHAR(50) NOT NULL, amount NUMERIC($1,$2) NOT NULL, summary VARCHAR(500), status VARCHAR(20) DEFAULT 'DRAFT', doc_id BIGINT, voucher_id BIGINT, bank_stmt_id BIGINT, attachment_ids TEXT, submitted_at TIMESTAMP, approved_at TIMESTAMP, created_by BIGINT, approved_by VARCHAR(100), reject_reason VARCHAR(500), created_at TIMESTAMP DEFAULT now(), updated_at TIMESTAMP DEFAULT now(), deleted INTEGER DEFAULT 0);

CREATE TABLE IF NOT EXISTS t_prepayment (id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL DEFAULT 1, vendor_id BIGINT NOT NULL, doc_id BIGINT, voucher_id BIGINT, period VARCHAR(6) NOT NULL, tx_date DATE NOT NULL, amount NUMERIC($1,$2) NOT NULL, settled_amount NUMERIC($1,$2) NOT NULL DEFAULT 0, unsettled_amount NUMERIC($1,$2) NOT NULL, summary VARCHAR(500), status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', source_doc_type VARCHAR(50), source_doc_id BIGINT, remark VARCHAR(500), created_by VARCHAR(64), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS t_reconciliation_exception (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, tenant_id BIGINT NOT NULL DEFAULT 1, source_doc_type VARCHAR(32) NOT NULL, -- receipt/payment/bank_txn source_doc_id BIGINT NOT NULL, target_doc_type VARCHAR(32), -- INVOICE_OUT/INVOICE_IN (可能为空) target_doc_id BIGINT, party_id BIGINT, -- 客户/供应商 ID party_type VARCHAR(20), -- CUSTOMER / VENDOR amount NUMERIC($1,$2) NOT NULL, unsettled_amount NUMERIC($1,$2), exception_type VARCHAR(32) NOT NULL, -- PARTY_MISMATCH / AMOUNT_MISMATCH / INVOICE_NOT_FOUND / MATCH_FAILED / APPROVAL_REQUIRED exception_reason VARCHAR(1000), match_suggestion VARCHAR(1000), -- AI/规则推荐的匹配方案 (JSON) status VARCHAR(20) NOT NULL DEFAULT 'OPEN', -- OPEN / RESOLVED / IGNORED retry_count INTEGER NOT NULL DEFAULT 0, assigned_to BIGINT, -- 处理人 resolved_by BIGINT, resolved_at TIMESTAMP, remark VARCHAR(500), created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS t_voucher (id BIGINT PRIMARY KEY, voucher_no VARCHAR(32) NOT NULL, period VARCHAR(6) NOT NULL, voucher_type_id BIGINT NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', total_debit NUMERIC($1,$2) NOT NULL DEFAULT 0, total_credit NUMERIC($1,$2) NOT NULL DEFAULT 0, summary VARCHAR(500), source VARCHAR(20) DEFAULT 'MANUAL', attachment_ids TEXT, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, submitted_by BIGINT, submitted_at TIMESTAMP, audited_by BIGINT, audited_at TIMESTAMP, posted_by BIGINT, posted_at TIMESTAMP, reversed_from BIGINT, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_voucher_no UNIQUE (voucher_no), CONSTRAINT chk_voucher_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'AUDITED', 'POSTED')), CONSTRAINT chk_voucher_source CHECK (source IN ('MANUAL', 'TEMPLATE', 'GENERATED', 'REVERSAL')), CONSTRAINT fk_voucher_type FOREIGN KEY (voucher_type_id) REFERENCES t_voucher_type(id));

CREATE TABLE IF NOT EXISTS t_voucher_entry (id BIGINT PRIMARY KEY, voucher_id BIGINT NOT NULL, subject_id BIGINT NOT NULL, debit NUMERIC($1,$2) NOT NULL DEFAULT 0, credit NUMERIC($1,$2) NOT NULL DEFAULT 0, summary VARCHAR(500), assist_json JSONB, sort_order INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_entry_voucher FOREIGN KEY (voucher_id) REFERENCES t_voucher(id) ON DELETE CASCADE, CONSTRAINT fk_entry_subject FOREIGN KEY (subject_id) REFERENCES t_subject(id), CONSTRAINT chk_entry_amount CHECK (debit >= 0 AND credit >= 0), CONSTRAINT chk_entry_not_both_zero CHECK (NOT (debit = 0 AND credit = 0)));

CREATE TABLE IF NOT EXISTS t_subject_balance (id BIGINT PRIMARY KEY, subject_id BIGINT NOT NULL, year INTEGER NOT NULL, period VARCHAR(6) NOT NULL, begin_balance NUMERIC($1,$2) NOT NULL DEFAULT 0, debit_total NUMERIC($1,$2) NOT NULL DEFAULT 0, credit_total NUMERIC($1,$2) NOT NULL DEFAULT 0, end_balance NUMERIC($1,$2) NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_balance_subject FOREIGN KEY (subject_id) REFERENCES t_subject(id), CONSTRAINT uq_subject_period UNIQUE (subject_id, period));

CREATE TABLE IF NOT EXISTS t_business_doc (id BIGINT PRIMARY KEY, doc_no VARCHAR(32) NOT NULL, doc_type VARCHAR(32) NOT NULL, doc_date DATE NOT NULL, period VARCHAR(6) NOT NULL, amount NUMERIC($1,$2) NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', supplier_id BIGINT, customer_id BIGINT, applicant_id BIGINT, dept_id BIGINT, summary VARCHAR(500), source VARCHAR(20) DEFAULT 'MANUAL', ocr_data JSONB, attachment_ids TEXT, voucher_id BIGINT, reversed_from BIGINT, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, submitted_by BIGINT, submitted_at TIMESTAMP, approved_by BIGINT, approved_at TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_doc_no_type UNIQUE (doc_type, doc_no), CONSTRAINT chk_doc_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'VOUCHERED', 'CLOSED', 'REJECTED')), CONSTRAINT chk_doc_type CHECK (doc_type IN ('RECEIPT', 'PAYMENT', 'EXPENSE', 'INVOICE_IN', 'INVOICE_OUT', 'OTHER_RECEIVABLE', 'OTHER_PAYABLE')));

CREATE TABLE IF NOT EXISTS t_business_doc_entry (id BIGINT PRIMARY KEY, doc_id BIGINT NOT NULL, expense_type VARCHAR(32), subject_id BIGINT, amount NUMERIC($1,$2) NOT NULL DEFAULT 0, invoice_no VARCHAR(64), assist_json JSONB, summary VARCHAR(500), sort_order INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_doc_entry_doc FOREIGN KEY (doc_id) REFERENCES t_business_doc(id) ON DELETE CASCADE, CONSTRAINT fk_doc_entry_subject FOREIGN KEY (subject_id) REFERENCES t_subject(id));

CREATE TABLE IF NOT EXISTS t_voucher_template (id BIGINT PRIMARY KEY, template_code VARCHAR(32) NOT NULL, template_name VARCHAR(64) NOT NULL, doc_type VARCHAR(32) NOT NULL, summary VARCHAR(500), entries JSONB NOT NULL, is_active BOOLEAN DEFAULT TRUE, remark VARCHAR(500), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_tpl_code UNIQUE (template_code));

CREATE TABLE IF NOT EXISTS t_bank_account (id BIGINT PRIMARY KEY, account_no VARCHAR(64) NOT NULL, account_name VARCHAR(128) NOT NULL, bank_name VARCHAR(128), currency VARCHAR(8) DEFAULT 'CNY', subject_id BIGINT, balance NUMERIC($1,$2) NOT NULL DEFAULT 0, is_active BOOLEAN DEFAULT TRUE, remark VARCHAR(500), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT fk_bank_account_subject FOREIGN KEY (subject_id) REFERENCES t_subject(id), CONSTRAINT uq_bank_account_no UNIQUE (account_no));

CREATE TABLE IF NOT EXISTS t_bank_journal (id BIGINT PRIMARY KEY, account_id BIGINT NOT NULL, tx_date DATE NOT NULL, period VARCHAR(6) NOT NULL, tx_type VARCHAR(20) NOT NULL, counter_account VARCHAR(128), amount NUMERIC($1,$2) NOT NULL, summary VARCHAR(500), business_doc_id BIGINT, voucher_id BIGINT, is_reconciled BOOLEAN DEFAULT FALSE, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT fk_journal_account FOREIGN KEY (account_id) REFERENCES t_bank_account(id), CONSTRAINT fk_journal_doc FOREIGN KEY (business_doc_id) REFERENCES t_business_doc(id), CONSTRAINT chk_journal_type CHECK (tx_type IN ('INCOME', 'EXPENSE', 'TRANSFER_IN', 'TRANSFER_OUT')));

CREATE TABLE IF NOT EXISTS t_bank_statement (id BIGINT PRIMARY KEY, account_id BIGINT NOT NULL, tx_date DATE NOT NULL, tx_type VARCHAR(20) NOT NULL, counter_account VARCHAR(128), amount NUMERIC($1,$2) NOT NULL, summary VARCHAR(500), external_no VARCHAR(64), raw_data JSONB, matched_journal_id BIGINT, match_status VARCHAR(20) DEFAULT 'UNMATCHED', imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT fk_statement_account FOREIGN KEY (account_id) REFERENCES t_bank_account(id), CONSTRAINT fk_statement_journal FOREIGN KEY (matched_journal_id) REFERENCES t_bank_journal(id), CONSTRAINT chk_stmt_type CHECK (tx_type IN ('INCOME', 'EXPENSE', 'TRANSFER_IN', 'TRANSFER_OUT')), CONSTRAINT chk_stmt_match_status CHECK (match_status IN ('UNMATCHED', 'MATCHED', 'MANUAL_MATCHED', 'IGNORED')));

CREATE TABLE IF NOT EXISTS t_reconciliation_suggestion (id BIGINT PRIMARY KEY, account_id BIGINT NOT NULL, statement_id BIGINT NOT NULL, journal_id BIGINT NOT NULL, score NUMERIC($1,$2) NOT NULL, status VARCHAR(20) DEFAULT 'PENDING', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, confirmed_at TIMESTAMP, CONSTRAINT fk_suggest_stmt FOREIGN KEY (statement_id) REFERENCES t_bank_statement(id), CONSTRAINT fk_suggest_journal FOREIGN KEY (journal_id) REFERENCES t_bank_journal(id), CONSTRAINT chk_suggest_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED')));

CREATE TABLE IF NOT EXISTS t_asset_category (id BIGINT PRIMARY KEY, code VARCHAR(32) NOT NULL, name VARCHAR(100) NOT NULL, parent_id BIGINT, level INTEGER NOT NULL DEFAULT 1, depreciation_method VARCHAR(20) DEFAULT 'STRAIGHT_LINE', useful_life INTEGER DEFAULT 5, residual_rate NUMERIC($1,$2) DEFAULT 0.05, asset_subject_id BIGINT, depreciation_subject_id BIGINT, expense_subject_id BIGINT, remark VARCHAR(500), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_asset_category_code UNIQUE (code), CONSTRAINT chk_dep_method CHECK (depreciation_method IN ('STRAIGHT_LINE', 'DOUBLE_DECLINING', 'SUM_OF_YEARS')));

CREATE TABLE IF NOT EXISTS t_asset_card (id BIGINT PRIMARY KEY, asset_code VARCHAR(32) NOT NULL, asset_name VARCHAR(200) NOT NULL, category_id BIGINT NOT NULL, spec VARCHAR(200), dept_id BIGINT, custodian_id BIGINT, acquisition_date DATE NOT NULL, original_value NUMERIC($1,$2) NOT NULL, residual_value NUMERIC($1,$2) NOT NULL DEFAULT 0, useful_life INTEGER NOT NULL, depreciation_method VARCHAR(20) DEFAULT 'STRAIGHT_LINE', status VARCHAR(20) NOT NULL DEFAULT 'IN_USE', location VARCHAR(200), serial_no VARCHAR(100), remark VARCHAR(500), accumulated_depreciation NUMERIC($1,$2) NOT NULL DEFAULT 0, net_value NUMERIC($1,$2) NOT NULL DEFAULT 0, last_depreciation_period VARCHAR(6), voucher_id BIGINT, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_asset_code UNIQUE (asset_code), CONSTRAINT fk_asset_category FOREIGN KEY (category_id) REFERENCES t_asset_category(id), CONSTRAINT chk_asset_status CHECK (status IN ('IN_USE', 'IDLE', 'DISPOSED', 'SCRAPPED')));

CREATE TABLE IF NOT EXISTS t_asset_change (id BIGINT PRIMARY KEY, asset_id BIGINT NOT NULL, change_type VARCHAR(20) NOT NULL, before_value VARCHAR(500), after_value VARCHAR(500), change_date DATE NOT NULL, voucher_id BIGINT, remark VARCHAR(500), created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT fk_change_asset FOREIGN KEY (asset_id) REFERENCES t_asset_card(id), CONSTRAINT chk_change_type CHECK (change_type IN ('VALUE_ADJUST', 'DEPT_TRANSFER', 'STATUS_CHANGE', 'DEPRECIATION')));

CREATE TABLE IF NOT EXISTS t_asset_depreciation (id BIGINT PRIMARY KEY, asset_id BIGINT NOT NULL, period VARCHAR(6) NOT NULL, depreciation_amount NUMERIC($1,$2) NOT NULL, accumulated_depreciation NUMERIC($1,$2) NOT NULL, net_value NUMERIC($1,$2) NOT NULL, voucher_id BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_dep_asset FOREIGN KEY (asset_id) REFERENCES t_asset_card(id), CONSTRAINT uq_dep_asset_period UNIQUE (asset_id, period));

CREATE TABLE IF NOT EXISTS t_asset_inventory (id BIGINT PRIMARY KEY, inventory_no VARCHAR(32) NOT NULL, inventory_date DATE NOT NULL, period VARCHAR(6) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', total_count INTEGER NOT NULL DEFAULT 0, profit_count INTEGER NOT NULL DEFAULT 0, loss_count INTEGER NOT NULL DEFAULT 0, voucher_id BIGINT, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_inventory_no UNIQUE (inventory_no), CONSTRAINT chk_inv_status CHECK (status IN ('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'VOUCHERED')));

CREATE TABLE IF NOT EXISTS t_asset_inventory_entry (id BIGINT PRIMARY KEY, inventory_id BIGINT NOT NULL, asset_id BIGINT NOT NULL, book_quantity INTEGER NOT NULL DEFAULT 1, actual_quantity INTEGER NOT NULL DEFAULT 0, diff_quantity INTEGER NOT NULL DEFAULT 0, diff_type VARCHAR(10), diff_amount NUMERIC($1,$2), remark VARCHAR(500), CONSTRAINT fk_inv_entry_inv FOREIGN KEY (inventory_id) REFERENCES t_asset_inventory(id) ON DELETE CASCADE, CONSTRAINT fk_inv_entry_asset FOREIGN KEY (asset_id) REFERENCES t_asset_card(id), CONSTRAINT chk_diff_type CHECK (diff_type IS NULL OR diff_type IN ('PROFIT', 'LOSS', 'NORMAL')));

CREATE TABLE IF NOT EXISTS t_asset_disposal (id BIGINT PRIMARY KEY, disposal_no VARCHAR(32) NOT NULL, asset_id BIGINT NOT NULL, disposal_type VARCHAR(20) NOT NULL, disposal_date DATE NOT NULL, period VARCHAR(6) NOT NULL, original_value NUMERIC($1,$2) NOT NULL, accumulated_depreciation NUMERIC($1,$2) NOT NULL, net_value NUMERIC($1,$2) NOT NULL, disposal_income NUMERIC($1,$2) NOT NULL DEFAULT 0, disposal_expense NUMERIC($1,$2) NOT NULL DEFAULT 0, gain_loss NUMERIC($1,$2) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', voucher_id BIGINT, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_disposal_no UNIQUE (disposal_no), CONSTRAINT fk_disposal_asset FOREIGN KEY (asset_id) REFERENCES t_asset_card(id), CONSTRAINT chk_disposal_type CHECK (disposal_type IN ('SCRAP', 'SALE', 'DONATE', 'INV_LOSS')), CONSTRAINT chk_disposal_status CHECK (status IN ('DRAFT', 'APPROVED', 'VOUCHERED')));

CREATE TABLE IF NOT EXISTS t_customer (id BIGINT PRIMARY KEY, code VARCHAR(32) NOT NULL, name VARCHAR(200) NOT NULL, contact_person VARCHAR(64), phone VARCHAR(32), email VARCHAR(128), address VARCHAR(500), tax_no VARCHAR(64), bank_name VARCHAR(128), bank_account VARCHAR(64), credit_limit NUMERIC($1,$2) DEFAULT 0, credit_days INTEGER DEFAULT 30, subject_id BIGINT, is_active BOOLEAN NOT NULL DEFAULT TRUE, remark VARCHAR(500), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_customer_code UNIQUE (code), CONSTRAINT fk_customer_subject FOREIGN KEY (subject_id) REFERENCES t_subject(id));

CREATE TABLE IF NOT EXISTS t_vendor (id BIGINT PRIMARY KEY, code VARCHAR(32) NOT NULL, name VARCHAR(200) NOT NULL, contact_person VARCHAR(64), phone VARCHAR(32), email VARCHAR(128), address VARCHAR(500), tax_no VARCHAR(64), bank_name VARCHAR(128), bank_account VARCHAR(64), credit_limit NUMERIC($1,$2) DEFAULT 0, credit_days INTEGER DEFAULT 30, subject_id BIGINT, is_active BOOLEAN NOT NULL DEFAULT TRUE, remark VARCHAR(500), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_vendor_code UNIQUE (code), CONSTRAINT fk_vendor_subject FOREIGN KEY (subject_id) REFERENCES t_subject(id));

CREATE TABLE IF NOT EXISTS t_receivable (id BIGINT PRIMARY KEY, customer_id BIGINT NOT NULL, doc_id BIGINT, voucher_id BIGINT, period VARCHAR(6) NOT NULL, tx_date DATE NOT NULL, amount NUMERIC($1,$2) NOT NULL, settled_amount NUMERIC($1,$2) NOT NULL DEFAULT 0, unsettled_amount NUMERIC($1,$2) NOT NULL, due_date DATE, summary VARCHAR(500), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT fk_recv_customer FOREIGN KEY (customer_id) REFERENCES t_customer(id), CONSTRAINT fk_recv_doc FOREIGN KEY (doc_id) REFERENCES t_business_doc(id));

CREATE TABLE IF NOT EXISTS t_payable (id BIGINT PRIMARY KEY, vendor_id BIGINT NOT NULL, doc_id BIGINT, voucher_id BIGINT, period VARCHAR(6) NOT NULL, tx_date DATE NOT NULL, amount NUMERIC($1,$2) NOT NULL, settled_amount NUMERIC($1,$2) NOT NULL DEFAULT 0, unsettled_amount NUMERIC($1,$2) NOT NULL, due_date DATE, summary VARCHAR(500), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT fk_pay_vendor FOREIGN KEY (vendor_id) REFERENCES t_vendor(id), CONSTRAINT fk_pay_doc FOREIGN KEY (doc_id) REFERENCES t_business_doc(id));

CREATE TABLE IF NOT EXISTS t_arap_settlement (id BIGINT PRIMARY KEY, settlement_no VARCHAR(32) NOT NULL, settlement_type VARCHAR(20) NOT NULL, settlement_date DATE NOT NULL, period VARCHAR(6) NOT NULL, party_id BIGINT NOT NULL, party_type VARCHAR(20) NOT NULL, total_amount NUMERIC($1,$2) NOT NULL, discount_amount NUMERIC($1,$2) DEFAULT 0, voucher_id BIGINT, status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_settlement_no UNIQUE (settlement_no), CONSTRAINT chk_settlement_type CHECK (settlement_type IN ('RECEIVE', 'PAY')), CONSTRAINT chk_settlement_party_type CHECK (party_type IN ('CUSTOMER', 'VENDOR')), CONSTRAINT chk_settlement_status CHECK (status IN ('DRAFT', 'CONFIRMED', 'VOUCHERED', 'REVERSED')));

CREATE TABLE IF NOT EXISTS t_arap_settlement_entry (id BIGINT PRIMARY KEY, settlement_id BIGINT NOT NULL, receivable_id BIGINT, payable_id BIGINT, settled_amount NUMERIC($1,$2) NOT NULL, discount_amount NUMERIC($1,$2) DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_settle_entry_settle FOREIGN KEY (settlement_id) REFERENCES t_arap_settlement(id) ON DELETE CASCADE, CONSTRAINT fk_settle_entry_recv FOREIGN KEY (receivable_id) REFERENCES t_receivable(id), CONSTRAINT fk_settle_entry_pay FOREIGN KEY (payable_id) REFERENCES t_payable(id), CONSTRAINT chk_settle_entry_one CHECK ((receivable_id IS NOT NULL AND payable_id IS NULL) OR (receivable_id IS NULL AND payable_id IS NOT NULL)));

CREATE TABLE IF NOT EXISTS t_bad_debt_provision (id BIGINT PRIMARY KEY, period VARCHAR(6) NOT NULL, method VARCHAR(20) NOT NULL, provision_date DATE NOT NULL, total_amount NUMERIC($1,$2) NOT NULL, voucher_id BIGINT, status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', remark VARCHAR(500), created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT chk_bad_debt_method CHECK (method IN ('AGING_RATIO', 'INDIVIDUAL', 'PERCENTAGE')), CONSTRAINT chk_bad_debt_status CHECK (status IN ('DRAFT', 'CONFIRMED', 'VOUCHERED')));

CREATE TABLE IF NOT EXISTS t_account_mapping_rule (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, item_keyword VARCHAR(255) NOT NULL, account_code VARCHAR(32) NOT NULL, account_name VARCHAR(128), direction VARCHAR(10) DEFAULT 'BOTH', aux_dimension JSONB DEFAULT '{}', priority INT DEFAULT 0, is_active BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS t_reconciliation_tolerance (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, tenant_id BIGINT NOT NULL DEFAULT 1, party_id BIGINT, party_type VARCHAR(20), tolerance_amount NUMERIC($1,$2) DEFAULT 5.00, tolerance_rate NUMERIC($1,$2) DEFAULT 10.00, effective_from DATE DEFAULT NOW(), effective_to DATE, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW(), deleted INTEGER DEFAULT 0);

CREATE TABLE IF NOT EXISTS t_tax_type (id BIGINT PRIMARY KEY, code VARCHAR(32) NOT NULL, name VARCHAR(100) NOT NULL, tax_category VARCHAR(20) NOT NULL, rate NUMERIC($1,$2) NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE, remark VARCHAR(500), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_tax_type_code UNIQUE (code), CONSTRAINT chk_tax_category CHECK (tax_category IN ('VAT_INPUT', 'VAT_OUTPUT', 'SURCHARGE', 'INCOME', 'OTHER')));

CREATE TABLE IF NOT EXISTS t_input_invoice (id BIGINT PRIMARY KEY, invoice_no VARCHAR(64) NOT NULL, invoice_date DATE NOT NULL, period VARCHAR(6) NOT NULL, vendor_id BIGINT, vendor_name VARCHAR(200), amount NUMERIC($1,$2) NOT NULL, tax_rate NUMERIC($1,$2) NOT NULL, tax_amount NUMERIC($1,$2) NOT NULL, total_amount NUMERIC($1,$2) NOT NULL, invoice_type VARCHAR(20) NOT NULL, certification_status VARCHAR(20) DEFAULT 'UNCERTIFIED', certified_date DATE, deduction_period VARCHAR(6), deduction_amount NUMERIC($1,$2), doc_id BIGINT, voucher_id BIGINT, remark VARCHAR(500), created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_input_invoice_no UNIQUE (invoice_no), CONSTRAINT fk_input_invoice_vendor FOREIGN KEY (vendor_id) REFERENCES t_vendor(id), CONSTRAINT chk_invoice_type CHECK (invoice_type IN ('SPECIAL', 'PLAIN', 'CUSTOMS', 'TRANSPORT')), CONSTRAINT chk_cert_status CHECK (certification_status IN ('UNCERTIFIED', 'CERTIFIED', 'INVALID', 'CANCELLED')));

CREATE TABLE IF NOT EXISTS t_output_invoice (id BIGINT PRIMARY KEY, invoice_no VARCHAR(64) NOT NULL, invoice_date DATE NOT NULL, period VARCHAR(6) NOT NULL, customer_id BIGINT, customer_name VARCHAR(200), amount NUMERIC($1,$2) NOT NULL, tax_rate NUMERIC($1,$2) NOT NULL, tax_amount NUMERIC($1,$2) NOT NULL, total_amount NUMERIC($1,$2) NOT NULL, invoice_type VARCHAR(20) NOT NULL, status VARCHAR(20) DEFAULT 'ISSUED', doc_id BIGINT, voucher_id BIGINT, remark VARCHAR(500), created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_output_invoice_no UNIQUE (invoice_no), CONSTRAINT fk_output_invoice_customer FOREIGN KEY (customer_id) REFERENCES t_customer(id), CONSTRAINT chk_output_invoice_type CHECK (invoice_type IN ('SPECIAL', 'PLAIN', 'CUSTOMS')), CONSTRAINT chk_output_invoice_status CHECK (status IN ('DRAFT', 'ISSUED', 'VOID', 'RED_INK')));

CREATE TABLE IF NOT EXISTS t_tax_carry_over (id BIGINT PRIMARY KEY, period VARCHAR(6) NOT NULL, tax_type VARCHAR(20) NOT NULL, output_tax NUMERIC($1,$2) DEFAULT 0, input_tax NUMERIC($1,$2) DEFAULT 0, payable_tax NUMERIC($1,$2) DEFAULT 0, surcharge_total NUMERIC($1,$2) DEFAULT 0, voucher_id BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT chk_carry_tax_type CHECK (tax_type IN ('VAT', 'SURCHARGE')), CONSTRAINT uq_carry_period_type UNIQUE (period, tax_type));

CREATE TABLE IF NOT EXISTS t_tax_declaration (id BIGINT PRIMARY KEY, declaration_no VARCHAR(32) NOT NULL, period VARCHAR(6) NOT NULL, tax_type VARCHAR(20) NOT NULL, declared_date DATE NOT NULL, payable_amount NUMERIC($1,$2) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', voucher_id BIGINT, remark VARCHAR(500), created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_declaration_no UNIQUE (declaration_no), CONSTRAINT chk_declaration_tax_type CHECK (tax_type IN ('VAT', 'SURCHARGE', 'INCOME')), CONSTRAINT chk_declaration_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'PAID')));

CREATE TABLE IF NOT EXISTS t_budget (id BIGINT PRIMARY KEY, budget_no VARCHAR(32) NOT NULL, period VARCHAR(6) NOT NULL, budget_type VARCHAR(20) NOT NULL, total_amount NUMERIC($1,$2) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', approved_by BIGINT, approved_at TIMESTAMP, remark VARCHAR(500), created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_by BIGINT, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_budget_no UNIQUE (budget_no), CONSTRAINT chk_budget_type CHECK (budget_type IN ('EXPENSE', 'REVENUE', 'CAPEX')), CONSTRAINT chk_budget_status CHECK (status IN ('DRAFT', 'APPROVED', 'ACTIVE', 'CLOSED')));

CREATE TABLE IF NOT EXISTS t_budget_entry (id BIGINT PRIMARY KEY, budget_id BIGINT NOT NULL, subject_id BIGINT, dept_id BIGINT, project_id BIGINT, period_month INTEGER, amount NUMERIC($1,$2) NOT NULL, control_type VARCHAR(20) NOT NULL DEFAULT 'WARN', used_amount NUMERIC($1,$2) NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_budget_entry_budget FOREIGN KEY (budget_id) REFERENCES t_budget(id) ON DELETE CASCADE, CONSTRAINT fk_budget_entry_subject FOREIGN KEY (subject_id) REFERENCES t_subject(id), CONSTRAINT chk_control_type CHECK (control_type IN ('WARN', 'APPROVE', 'BLOCK')));

CREATE TABLE IF NOT EXISTS t_budget_adjustment (id BIGINT PRIMARY KEY, adjustment_no VARCHAR(32) NOT NULL, budget_id BIGINT NOT NULL, adjustment_type VARCHAR(20) NOT NULL, adjustment_date DATE NOT NULL, period VARCHAR(6) NOT NULL, adjustment_amount NUMERIC($1,$2) NOT NULL, reason VARCHAR(500), status VARCHAR(20) NOT NULL DEFAULT 'DRAFT', approved_by BIGINT, approved_at TIMESTAMP, created_by BIGINT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted INTEGER NOT NULL DEFAULT 0, CONSTRAINT uq_adjustment_no UNIQUE (adjustment_no), CONSTRAINT fk_adjustment_budget FOREIGN KEY (budget_id) REFERENCES t_budget(id), CONSTRAINT chk_adjustment_type CHECK (adjustment_type IN ('INCREASE', 'DECREASE', 'TRANSFER')), CONSTRAINT chk_adjustment_status CHECK (status IN ('DRAFT', 'APPROVED', 'REJECTED')));
