-- ============================================================
-- V151: 新增期末结账日志表 t_close_log
--
-- P85：记录每次结账相关动作（检查/生成/审核记账/结账/反结账），
-- 供 /period-close/log 查询与审计追踪。替代 PeriodCloseService.listCloseLog()
-- 原有的空实现。
--
-- 设计要点：
--   1. 操作者单独用 operator_id 列持久化。不复用 t_close_log 的 created_by
--      列 —— BaseEntity.createdBy 带 @TableField(exist=false)，MyBatis-Plus
--      会忽略该字段，写进去也不会落库。
--   2. 只追加不改写：结账日志是审计凭据，应用层不提供 update/delete 入口。
--   3. duration_ms 记录动作耗时，便于定位慢结账。
--   4. id 用 GENERATED BY DEFAULT AS IDENTITY（不用 BIGSERIAL）。
--      项目的 SchemaValidator 在应用启动时检查全部企业级表 id 列 must be IDENTITY，
--      BIGSERIAL 的 is_identity=NO 会直接启动失败（同 V92/V93 修复模式）。
--      BY DEFAULT 而非 ALWAYS：允许显式插入 id，与其他测试表插入方式一致。
-- ============================================================

CREATE TABLE IF NOT EXISTS t_close_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period      VARCHAR(6)    NOT NULL,
    action      VARCHAR(20)   NOT NULL,
    operator_id BIGINT,
    result      VARCHAR(10)   NOT NULL DEFAULT 'success',
    detail      TEXT,
    duration_ms BIGINT,
    enterprise_id BIGINT,
    created_at  TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP,
    deleted     INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT chk_close_log_result CHECK (result IN ('success', 'fail'))
);

COMMENT ON TABLE  t_close_log              IS '期末结账日志（P85，只追加不改写）';
COMMENT ON COLUMN t_close_log.period       IS '会计期间 YYYYMM';
COMMENT ON COLUMN t_close_log.action       IS 'CHECK/GENERATE/REVIEW_POST/CLOSE/REOPEN';
COMMENT ON COLUMN t_close_log.operator_id  IS '操作者 ID';
COMMENT ON COLUMN t_close_log.result       IS 'success / fail';
COMMENT ON COLUMN t_close_log.detail       IS '明细：成功时凭证号清单，失败时异常消息';
COMMENT ON COLUMN t_close_log.duration_ms  IS '耗时毫秒';

-- 查询主路径：按期间倒序查看某期间的结账流水
CREATE INDEX IF NOT EXISTS idx_close_log_period ON t_close_log (period, created_at DESC);
