-- ============================================================
-- V93: 修复所有 t_ 表的 id 列缺少 IDENTITY 属性
-- 根因：V1 baseline 中所有表的 id 定义为 BIGINT PRIMARY KEY
--       但 Entity 统一使用 @TableId(type = IdType.AUTO) 依赖自增
-- 修复：给所有 t_ 表的 id 列添加 GENERATED ALWAYS AS IDENTITY
-- 说明：对已有数据的表，PostgreSQL 自动取 max(id)+1 作为起始值
-- ============================================================

-- ===== 以下表在 V92 中已修复，此处跳过（保持幂等性） =====
-- t_subject: V92 已修复

-- ===== 其余所有 t_ 表 =====
ALTER TABLE t_account_mapping_rule ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_aging_alert ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_ai_feedback_log ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_ai_task ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_arap_settlement ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_arap_settlement_entry ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_asset_card ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_asset_category ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_asset_change ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_asset_depreciation ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_asset_disposal ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_asset_inventory ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_asset_inventory_entry ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_audit_log ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_aux_dimension ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_bad_debt_detail ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_bad_debt_provision ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_bad_debt_scheme ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_bank_account ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_bank_journal ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_bank_statement ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_budget ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_business_doc ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_business_doc_entry ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_customer ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_customer_statement ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_dept ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_employee ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_expense_reimbursement ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_input_invoice ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_menu ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_note_receivable ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_output_invoice ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_period ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_reconciliation_exception ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_reconciliation_suggestion ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_reconciliation_tolerance ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_report_template ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_role ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_role_menu ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_subject_balance ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_summary_lib ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_sys_config ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_tax_carry_over ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_tax_declaration ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_tax_type ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_user ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_user_role ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_vendor ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_voucher ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_voucher_entry ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_voucher_template ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE t_voucher_type ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
